# Flash Cast 应用配置文件
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Spring 配置
spring:
  application:
    name: flash-cast-backend
  main:
    allow-circular-references: true
    # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: admin

    # Druid连接池配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin

  # MyBatis配置
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
    mapper-locations: classpath:mapper/*.xml
  
  # JSON 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# MyBatis Plus 配置
mybatis-plus:
  # Mapper XML 文件位置
  mapper-locations: classpath*:mapper/**/*.xml
  # 实体类包路径
  type-aliases-package: com.flashcast.*.entity
  # 全局配置
  global-config:
    # 数据库配置
    db-config:
      # 主键类型
      id-type: auto
      # 逻辑删除字段
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 字段验证策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
  # 配置项
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 开启二级缓存
    cache-enabled: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.flashcast: DEBUG
    com.baomidou.mybatisplus: DEBUG

# JWT 配置
jwt:
  secret: flashcast_jwt_secret_key_2024_very_long_and_secure_key_for_production_use
  expire: 604800000 # 7天（毫秒）

# Swagger 文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.flashcast.controller

domain:
  comfy: http://localhost:8081
  ai-server: http://localhost:8081

app:
  jwt:
    secret: 8ZkP!xQ3@vT6$bN9#sF2&dR5*gH7^jK1+mU4%pL0(wE8)yA3

resource:
  path: /Users/king/resources/

